/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialogUser.java
 *
 * Created on May 22, 2011, 1:19:26 AM
 */

package apotik;

import data.dtUser;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sql.dbBackground;
import sql.dbUser;
import tm.tmUser;

/**
 *
 * @author sad
 */
public class dialogUser extends javax.swing.JDialog {

    /** Creates new form dialogUser */
    public dialogUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground();
        Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2, (dim.height - abounds.height) / 2);
        this.jTable1.setModel(this.tmUser);

        ListSelectionModel lsm = this.jTable1.getSelectionModel();
        lsm.addListSelectionListener(new TabKeField());

        this.jTable1.setSelectionMode(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background1 = new tampilan.background();
        panelRuncing1 = new tampilan.panelRuncing();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        botton1 = new tampilan.botton();
        botton2 = new tampilan.botton();
        botton3 = new tampilan.botton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("UserName :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Akses :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Semua Akses Halaman");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Form Penjualan Akses");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRuncing1Layout = new javax.swing.GroupLayout(panelRuncing1);
        panelRuncing1.setLayout(panelRuncing1Layout);
        panelRuncing1Layout.setHorizontalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panelRuncing1Layout.setVerticalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/new.png"))); // NOI18N
        botton1.setText("Tambah Akun");
        botton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton1ActionPerformed(evt);
            }
        });

        botton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/update.png"))); // NOI18N
        botton2.setText("Edit");
        botton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton2ActionPerformed(evt);
            }
        });

        botton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/delete.png"))); // NOI18N
        botton3.setText("Hapus");
        botton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(panelRuncing1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background1Layout.createSequentialGroup()
                        .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(background1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void botton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton1ActionPerformed
    dtUser dtu = new dtUser();
    dtu.setUserName(this.jTextField1.getText());
    dtu.setPassword(this.jPasswordField1.getText());
    if (this.jRadioButton1.isSelected())
      dtu.setAkses(0);
    else dtu.setAkses(1);

    if (this.dbUser.insert(dtu))
      this.tmUser.insert(dtu);
    }//GEN-LAST:event_botton1ActionPerformed

    private void botton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton2ActionPerformed
    int n = this.jTable1.getSelectedRow();
    if (n >= 0) {
      dtUser dtu = new dtUser();
      dtu.setUserName(this.jTextField1.getText());
      dtu.setPassword(this.jPasswordField1.getText());
      if (this.jRadioButton1.isSelected())
        dtu.setAkses(0);
      else dtu.setAkses(1);

      if (this.dbUser.edit(dtu, ((dtUser)tmUser.fieldUser.get(n)).getUserName()))
        this.tmUser.update(dtu, n);
    }
    else {
      JOptionPane.showMessageDialog(this.rootPane, "Pilih data yang akan di rubah", "ERROT", 0);
    }
    }//GEN-LAST:event_botton2ActionPerformed

    private void botton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton3ActionPerformed
    int n = this.jTable1.getSelectedRow();

    if (n >= 0) {
      if ((JOptionPane.showConfirmDialog(this.rootPane, "Yakin???", "Delete", 0) == 0) &&
        (this.dbUser.delete(((dtUser)tmUser.fieldUser.get(n)).getUserName()))) {
        this.tmUser.delete(n);
      }
    }
    else
      JOptionPane.showMessageDialog(this.rootPane, "Pilih data yang akan di hapus", "ERROT", 0);
    }//GEN-LAST:event_botton3ActionPerformed


    tmUser tmUser=new tmUser();
    dbUser dbUser=new dbUser();
    dbBackground dbBackground=new dbBackground();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tampilan.background background1;
    private tampilan.botton botton1;
    private tampilan.botton botton2;
    private tampilan.botton botton3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private tampilan.panelRuncing panelRuncing1;
    // End of variables declaration//GEN-END:variables
    private void setBackground(){
        int n=dbBackground.reload();
        if(n==1) {
            background1.setGambar("background1.jpg");
        }
        else if(n==2) {
            background1.setGambar("background2.jpg");
        }
        else if(n==3) {
            background1.setGambar("background3.jpg");
        }
        else if(n==4) {
            background1.setGambar("background4.jpg");
        }
        else if(n==5) {
            background1.setGambar("background5.jpg");
        }

    }

  class TabKeField implements ListSelectionListener {
    TabKeField() {
    }

    public void valueChanged(ListSelectionEvent e) {
      if (e.getValueIsAdjusting()) return;
      ListSelectionModel lsm = (ListSelectionModel)e.getSource();
      int n = lsm.getMinSelectionIndex();
      try {
        jTextField1.setText(((dtUser)tmUser.fieldUser.get(n)).getUserName());
        jPasswordField1.setText(((dtUser)tmUser.fieldUser.get(n)).getPassword());
        if (((dtUser)tmUser.fieldUser.get(n)).getAkses() == 0)
          jRadioButton1.setSelected(true);
        else
          jRadioButton2.setSelected(true);
      }
      catch (Exception z) {
        jTextField1.setText("");
        jPasswordField1.setText("");
        jRadioButton1.setSelected(true);
      }
    }
  }

}
