/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialogKatagori.java
 *
 * Created on Mar 10, 2011, 1:04:37 AM
 */

package apotik;

import data.dtKatagori;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
import sql.dbkatagori;
import tm.tmKatagori;


/**
 *
 * @author SAD
 */
public class dialogKatagori extends javax.swing.JDialog {

    /** Creates new form dialogKatagori */
    public dialogKatagori(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2,(dim.height - abounds.height) / 2);

        jTable1.setModel(tmKatagori);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new tampilan.background();
        panelRuncing1 = new tampilan.panelRuncing();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        botton1 = new tampilan.botton();
        botton3 = new tampilan.botton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Katagori Obat");
        setResizable(false);

        panelRuncing1.setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "KATAGORI OBAT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nama katagori :");

        botton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/new.png"))); // NOI18N
        botton1.setText("Tambah");
        botton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        botton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton1ActionPerformed(evt);
            }
        });

        botton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/delete.png"))); // NOI18N
        botton3.setText("Hapus");
        botton3.setFont(new java.awt.Font("Tahoma", 1, 11));
        botton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRuncing1Layout = new javax.swing.GroupLayout(panelRuncing1);
        panelRuncing1.setLayout(panelRuncing1Layout);
        panelRuncing1Layout.setHorizontalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRuncing1Layout.createSequentialGroup()
                        .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botton3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                    .addGroup(panelRuncing1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRuncing1Layout.setVerticalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRuncing1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(background1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton1ActionPerformed
        if(!jTextField1.getText().trim().equals("")){
            dtKatagori dtk=new dtKatagori();
            dtk.setNamaKatagori(jTextField1.getText());

            if(dbk.insert(dtk))
                tmKatagori.insert(dtk);
            jTextField1.setText("");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Isi Katagoti Obat !!!","ERROT",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botton1ActionPerformed

    private void botton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton3ActionPerformed
        int n=jTable1.getSelectedRow();
        if(n>=0){
            if(dbk.delete(tmKatagori.fieldKatagoriObat.get(n).getNamaKatagori()))
            tmKatagori.delete(n);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Pilih data yang akan di hapus","ERROT",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botton3ActionPerformed

    tmKatagori tmKatagori=new tmKatagori();
    dbkatagori dbk=new dbkatagori();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tampilan.background background1;
    private tampilan.botton botton1;
    private tampilan.botton botton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private tampilan.panelRuncing panelRuncing1;
    // End of variables declaration//GEN-END:variables

}
