/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * transaksi.java
 *
 * Created on Mar 9, 2011, 12:54:27 PM
 */

package apotik;

import data.dtPenjualan;
import data.dtPenjualanDet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import sql.dbBackground;
import sql.dbObat;
import sql.dbPenjualan;
import sql.dbPenjualanDet;
import sql.koneksiAcces;
import tm.tmPelanggan;
import tm.tmPenjualan;
import tm.tmTableObat;
import tm.tmTemp;

/**
 *
 * @author SAD
 */
public class transaksi extends javax.swing.JFrame {

    /** Creates new form transaksi */
    public transaksi() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|this.MAXIMIZED_BOTH);
        jDateChooser1.setDate(new Date());
        jTable1.setModel(tmTemp);

        lebarKolomTabel();
        setNota();
        setBackground();
        zzz();

        tmTemp.removeAll();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        background1 = new tampilan.background();
        panelRuncing1 = new tampilan.panelRuncing();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        panelRuncing2 = new tampilan.panelRuncing();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botton1 = new tampilan.botton();
        panelBiasa1 = new tampilan.panelBiasa();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelBiasa3 = new tampilan.panelBiasa();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        panelRuncing3 = new tampilan.panelRuncing();
        panelRuncing4 = new tampilan.panelRuncing();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi Penjualan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        background1.setEnabled(false);
        background1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Tanggal Transaksi :");

        jDateChooser1.setDateFormatString("d/MM/yyyy H:m:s");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Identitas :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Konsumen Biasa", "Pelanggan", "Tebus Obat" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Pembayaran :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunai", "1 Minggu", "2 Minggu", "3 Minggu", "1 Bulan", "3 Bulan", "1 Tahun", "Lainya" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(10)));
        jSpinner1.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12));
        jLabel4.setText("hari");

        jButton3.setText("...");
        jButton3.setEnabled(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField10.setEnabled(false);

        javax.swing.GroupLayout panelRuncing1Layout = new javax.swing.GroupLayout(panelRuncing1);
        panelRuncing1.setLayout(panelRuncing1Layout);
        panelRuncing1Layout.setHorizontalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRuncing1Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRuncing1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 156, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRuncing1Layout.setVerticalGroup(
            panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTable1HierarchyChanged(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTable1VetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/delete.png"))); // NOI18N
        botton1.setText("Hapus Daftar Penjualan");
        botton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        botton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRuncing2Layout = new javax.swing.GroupLayout(panelRuncing2);
        panelRuncing2.setLayout(panelRuncing2Layout);
        panelRuncing2Layout.setHorizontalGroup(
            panelRuncing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRuncing2Layout.setVerticalGroup(
            panelRuncing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Kode Barang & Jumlah Barang");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        jButton1.setText("...");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Masukan Transaksi");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBiasa1Layout = new javax.swing.GroupLayout(panelBiasa1);
        panelBiasa1.setLayout(panelBiasa1Layout);
        panelBiasa1Layout.setHorizontalGroup(
            panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBiasa1Layout.createSequentialGroup()
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addGroup(panelBiasa1Layout.createSequentialGroup()
                        .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBiasa1Layout.setVerticalGroup(
            panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Default No. Nota");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField7.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("Cash :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Cash Back :");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelBiasa3Layout = new javax.swing.GroupLayout(panelBiasa3);
        panelBiasa3.setLayout(panelBiasa3Layout);
        panelBiasa3Layout.setHorizontalGroup(
            panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa3Layout.createSequentialGroup()
                .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBiasa3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(panelBiasa3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelBiasa3Layout.setVerticalGroup(
            panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Total Penjualan :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Diskon (%) :");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField3.setText("0");
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField5.setText("0");
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);

        jLabel8.setText("---------------------------------------------------------------------");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Grand Total :");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField6.setText("0");
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField6.setEnabled(false);

        jSpinner3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinner3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSpinner3InputMethodTextChanged(evt);
            }
        });
        jSpinner3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner3PropertyChange(evt);
            }
        });
        jSpinner3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinner3KeyReleased(evt);
            }
        });
        jSpinner3.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jSpinner3VetoableChange(evt);
            }
        });

        javax.swing.GroupLayout panelRuncing4Layout = new javax.swing.GroupLayout(panelRuncing4);
        panelRuncing4.setLayout(panelRuncing4Layout);
        panelRuncing4Layout.setHorizontalGroup(
            panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing4Layout.createSequentialGroup()
                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRuncing4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addGroup(panelRuncing4Layout.createSequentialGroup()
                                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addGroup(panelRuncing4Layout.createSequentialGroup()
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))))
                    .addGroup(panelRuncing4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRuncing4Layout.setVerticalGroup(
            panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRuncing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRuncing3Layout = new javax.swing.GroupLayout(panelRuncing3);
        panelRuncing3.setLayout(panelRuncing3Layout);
        panelRuncing3Layout.setHorizontalGroup(
            panelRuncing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRuncing3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRuncing3Layout.setVerticalGroup(
            panelRuncing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuncing3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Save Transaksi non Tunai");
        jButton4.setEnabled(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRuncing2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRuncing1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(panelBiasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(panelRuncing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBiasa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuncing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRuncing2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBiasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRuncing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background1Layout.createSequentialGroup()
                        .addComponent(panelBiasa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(background1, java.awt.BorderLayout.CENTER);

        jMenu7.setText("File");

        jMenuItem1.setText("LogOut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed1(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Menu");

        jMenuItem3.setText("Reset Transaksi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem4.setText("Save Transaksi");
        jMenuItem4.setEnabled(false);
        jMenu8.add(jMenuItem4);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dialogSearchObat dso=new dialogSearchObat(this, rootPaneCheckingEnabled);
        dso.setVisible(true);
        if(!dso.kode.equals(""))
            jTextField2.setText(dso.kode);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x=tmTableObat.search(jTextField2.getText());
        int y=tmTemp.search(jTextField2.getText());

        if(x!=-1 && y==-1){
            int bny=Integer.parseInt(jSpinner2.getValue().toString());

            if(tmTableObat.persediaan(jTextField2.getText(),bny)==-1){

                dtPenjualanDet dtpd=new dtPenjualanDet();
                dtpd.setKodeObat(tmTableObat.fieldObat.get(x).getKodeObat());
                dtpd.setNamaObat(tmTableObat.fieldObat.get(x).getNamaObat());

                float harga=0;

                if(jComboBox1.getSelectedIndex()==0)
                    harga=(float) tmTableObat.fieldObat.get(x).gethUmum();
                else if(jComboBox1.getSelectedIndex()==1)
                    harga=(float) tmTableObat.fieldObat.get(x).gethPelanggan();
                else if(jComboBox1.getSelectedIndex()==2)
                    harga=(float) tmTableObat.fieldObat.get(x).gethResep();

                dtpd.setHarga(harga);

                dtpd.setBny(bny);
                float total=harga*bny;
                dtpd.setTotal(total);
                int disc=0;
                dtpd.setDisc(disc);
                float subTotal=total-((disc/100)*total);
                dtpd.setSubTotal(subTotal);

                tmTemp.insert(dtpd);

                allTransaksi();
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Stok Barang Tidak Mencukupi","ERROT",JOptionPane.ERROR_MESSAGE);
        }
        else if(x==-1)
            JOptionPane.showMessageDialog(rootPane, "Data Obat Tidak Di Temukan","ERROT",JOptionPane.ERROR_MESSAGE);
        else if(y!=-1)
            JOptionPane.showMessageDialog(rootPane, "Data Obat Sudah Dalam Daftar","ERROT",JOptionPane.ERROR_MESSAGE);
        this.jDateChooser1.setDate(new Date());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()==1){
            jButton3.setEnabled(true);
        }
        else{
            jButton3.setEnabled(false);
        }
        jTextField10.setText("");
        jTextField1.setText("");
        tmTemp.updateharga(jComboBox1.getSelectedIndex());

        allTransaksi();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedIndex()==0){
            jButton4.setEnabled(false);
            jTextField8.setEditable(true);
            jTextField9.setEditable(true);
        }
        else if(jComboBox2.getSelectedIndex() == 7)
        {
            jSpinner1.setEnabled(true);
            jButton4.setEnabled(true);
        }
        else{
            jButton4.setEnabled(true);
            jSpinner1.setEnabled(false);
            jTextField8.setEditable(false);
            jTextField9.setEditable(false);
        }



    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jTextField7.setEnabled(false);
            jTextField7.requestFocus();
            
        }
        else{
            jTextField7.setEnabled(true);
            jTextField7.requestFocus();
            
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void botton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton1ActionPerformed
        int n=jTable1.getSelectedRow();
        if(n>=0){
            tmTemp.delete(n);
            allTransaksi();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Pilih data yang akan di hapus","ERROT",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botton1ActionPerformed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
  
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jTable1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable1HierarchyChanged
        //allTransaksi();
    }//GEN-LAST:event_jTable1HierarchyChanged

    private void jTable1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTable1VetoableChange
        //allTransaksi();
    }//GEN-LAST:event_jTable1VetoableChange

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        allTransaksi();
    }//GEN-LAST:event_jTable1PropertyChange

    private void jSpinner3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner3PropertyChange
        allTransaksi();
    }//GEN-LAST:event_jSpinner3PropertyChange

    private void jSpinner3VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jSpinner3VetoableChange
        
    }//GEN-LAST:event_jSpinner3VetoableChange

    private void jSpinner3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner3KeyReleased
        
    }//GEN-LAST:event_jSpinner3KeyReleased

    private void jSpinner3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinner3InputMethodTextChanged
        allTransaksi();
    }//GEN-LAST:event_jSpinner3InputMethodTextChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dialogPelanggan dp=new dialogPelanggan(this, rootPaneCheckingEnabled);
        dp.setVisible(true);
        int n=dp.getN();
        if(n!=-1){
            jTextField10.setText(tmlanggan.fieldPelanggan.get(n).getKodePelanggan());
            jTextField1.setText(tmlanggan.fieldPelanggan.get(n).getNamaPelanggan());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped

    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        try{
            nominal=Integer.parseInt(jTextField8.getText());
        }
        catch(Exception x){
            nominal=0;
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        int keyCode = evt.getKeyCode();
        int x = 13; //0 --> true 2 --> false
        
        
        if (keyCode == evt.VK_ENTER){
            if(nominal>=grandTotal && tmTemp.fieldTemp.size()>0){
                x=JOptionPane.showConfirmDialog(rootPane, "Simpan Transaksi ini ????","Konfirmasi ",JOptionPane.OK_CANCEL_OPTION);
                if(x==0){

                    dtPenjualan dtp=new dtPenjualan();
                    dtp.setNoNota(jTextField7.getText());
                    dtp.setIdKonsumen(jTextField10.getText());
                    dtp.setTotal(total);
                    dtp.setDiskon((int) disc);
                    dtp.setGrandTotal(grandTotal);
                    dtp.setTglTransaksi(jDateChooser1.getDate());
                    if(jComboBox2.getSelectedIndex()==0){
                        dtp.setKet(1);
                        dtp.setTglBayar(jDateChooser1.getDate());
                    }
                    else {
                        dtp.setKet(2);
                        
                    }
                    if (dbPenjualan.insert(dtp)) {
                        tmp.insert(dtp);
                        int n = 0;
                        while (n < tmTemp.fieldTemp.size()) {
                          dtPenjualanDet dtpd = new dtPenjualanDet();
                          dtpd.setNoNota(this.jTextField7.getText());
                          dtpd.setKodeObat(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat());
                          dtpd.setNamaObat(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getNamaObat());
                          dtpd.setHarga(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getHarga());
                          dtpd.setBny(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny());
                          dtpd.setTotal(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getTotal());
                          dtpd.setDisc(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getDisc());
                          dtpd.setSubTotal(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getSubTotal());

                          if (this.dbPenjualanDet.insert(dtpd))
                          {
                            if (this.dbObat.editObat2(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat(), ((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny())) {
                              this.tmTableObat.updateStok(this.tmTableObat.search(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat()), ((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny(), true);
                            }
                          }

                          n++;
                        }               
                    }
                    reset();
                }
            }
            else if(tmTemp.fieldTemp.size()==0)
                JOptionPane.showMessageDialog(rootPane, "Isi Transaksi Terlebih Dahulu???","ERROR",JOptionPane.ERROR_MESSAGE);
            else if(nominal==0)
                JOptionPane.showMessageDialog(rootPane, "Masukan uang Konsumen","ERROR",JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Pembayaran Tidak Mencukupi","ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jTextField8KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if (Main.akses == 0) {
      new formUtama().setVisible(true);
    } else {
      try {
        koneksiAcces.stat.close();
        koneksiAcces.kon.close();
      }
      catch (SQLException ex) {
      }
      System.exit(0);
    }
    }//GEN-LAST:event_formWindowClosing

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
         int keyCode = evt.getKeyCode();
        if (keyCode == evt.VK_LEFT)
            JOptionPane.showMessageDialog(rootPane, "asasas As");
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
         int keyCode = evt.getKeyCode();
        if (keyCode == evt.VK_LEFT)
            JOptionPane.showMessageDialog(rootPane, "asasas As");
    }//GEN-LAST:event_formKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            if(tmTemp.fieldTemp.size()>0){
               int x=JOptionPane.showConfirmDialog(rootPane, "Simpan Transaksi ini ????","Konfirmasi ",JOptionPane.OK_CANCEL_OPTION);
                if(x==0){
                    dtPenjualan dtp=new dtPenjualan();
                    dtp.setNoNota(jTextField7.getText());
                    dtp.setIdKonsumen(jTextField10.getText());
                    dtp.setTotal(total);
                    dtp.setDiskon((int) disc);
                    dtp.setGrandTotal(grandTotal);
                    dtp.setTglTransaksi(jDateChooser1.getDate());

                    SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
                    String ddmmyyyy=sdf.format(jDateChooser1.getDate());
                    int dd=Integer.parseInt(ddmmyyyy.substring(0, 2));
                    int mm=Integer.parseInt(ddmmyyyy.substring(2, 4));
                    int yy=Integer.parseInt(ddmmyyyy.substring(4));

                    Calendar c1 = Calendar.getInstance();
                    c1.set(yy, mm-1 , dd);

                    if(jComboBox2.getSelectedIndex()==0)
                        dtp.setKet(1);
                    else if(jComboBox2.getSelectedIndex()==1){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +7);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==2){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +14);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==3){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +21);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==4){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +30);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==5){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +90);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==6){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +360);
                        dtp.setTglBayar(c1.getTime());
                    }
                    else if(jComboBox2.getSelectedIndex()==7){
                        dtp.setKet(2);
                        c1.add(Calendar.DAY_OF_WEEK, +Integer.valueOf(jSpinner1.getValue().toString()));
                        dtp.setTglBayar(c1.getTime());
                    }
                    if (dbPenjualan.insert(dtp)) {
                        tmp.insert(dtp);
                        int n = 0;
                        while (n < tmTemp.fieldTemp.size()) {
                          dtPenjualanDet dtpd = new dtPenjualanDet();
                          dtpd.setNoNota(this.jTextField7.getText());
                          dtpd.setKodeObat(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat());
                          dtpd.setNamaObat(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getNamaObat());
                          dtpd.setHarga(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getHarga());
                          dtpd.setBny(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny());
                          dtpd.setTotal(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getTotal());
                          dtpd.setDisc(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getDisc());
                          dtpd.setSubTotal(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getSubTotal());

                          if (this.dbPenjualanDet.insert(dtpd))
                          {
                            if (this.dbObat.editObat2(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat(), ((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny())) {
                              this.tmTableObat.updateStok(this.tmTableObat.search(((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getKodeObat()), ((dtPenjualanDet)tmTemp.fieldTemp.get(n)).getBny(), true);
                            }
                          }

                          n++;
                        }
                    }

                    reset();

                }
            }
            else if(jTextField10.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane, "harus mengisi daftar pelanggan","ERROR",JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Masukan Daftar Pembelian","ERROR",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        logIn lg=new logIn();
        lg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed1
        try {
          koneksiAcces.stat.close();
          koneksiAcces.kon.close();
        }
        catch (SQLException ex) {
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed1

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        reset();
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    float nominal=0;
    tmTemp tmTemp=new tmTemp();
    tmTableObat tmTableObat=new tmTableObat();
    tmPenjualan tmp=new tmPenjualan();
    tmPelanggan tmlanggan=new tmPelanggan();

    dbBackground dbBackground=new dbBackground();
    dbPenjualan dbPenjualan=new dbPenjualan();
    dbPenjualanDet dbPenjualanDet=new dbPenjualanDet();
    dbObat dbObat=new dbObat();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tampilan.background background1;
    private tampilan.botton botton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private tampilan.panelBiasa panelBiasa1;
    private tampilan.panelBiasa panelBiasa3;
    private tampilan.panelRuncing panelRuncing1;
    private tampilan.panelRuncing panelRuncing2;
    private tampilan.panelRuncing panelRuncing3;
    private tampilan.panelRuncing panelRuncing4;
    // End of variables declaration//GEN-END:variables

    float total=0;
    float disc=0;
    float grandTotal=0;
    DecimalFormat dfo = new DecimalFormat("#,##0");
    private void allTransaksi(){
        
        int n=0;
        total=0;
        try{
            while(n<tmTemp.fieldTemp.size()){
                total=total+tmTemp.fieldTemp.get(n).getSubTotal();
                n++;
            }

            disc=Integer.parseInt(jSpinner3.getValue().toString());
           
            float potongan=disc/100*total;
            grandTotal=total-potongan;
            
            jTextField3.setText("Rp. "+dfo.format(total));
            jTextField5.setText("Rp. "+dfo.format(potongan));
            jTextField6.setText("Rp. "+dfo.format(grandTotal));
        }
        catch(Exception z){
            jTextField3.setText("Rp. 0");
            jTextField5.setText("Rp. 0");
            jTextField6.setText("Rp. 0");
        }
    }

    private void reset(){
        this.tmTemp.removeAll();
        allTransaksi();
        this.jComboBox1.setSelectedIndex(0);

        this.jComboBox2.setSelectedIndex(0);
        this.jSpinner1.setEnabled(false);

        setNota();
        this.jTextField8.setText("");
        this.jTextField9.setText("");
        this.jDateChooser1.setDate(new Date());
        this.jTextField2.setText("");
        jSpinner2.setValue(1);
        jSpinner3.setValue(0);
    }

            
    SimpleDateFormat ddd=new SimpleDateFormat("ddMMyyyy.HHmmss.");
    private void setNota(){
        jTextField7.setText(ddd.format(new Date())+ String.valueOf(tmPenjualan.fieldPenjualan.size()+1));
    }

    private void setBackground(){
        int n=dbBackground.reload();
        if(n==1) {
            background1.setGambar("background1.jpg");
        }
        else if(n==2) {
            background1.setGambar("background2.jpg");
        }
        else if(n==3) {
            background1.setGambar("background3.jpg");
        }
        else if(n==4) {
            background1.setGambar("background4.jpg");
        }
        else if(n==5) {
            background1.setGambar("background5.jpg");
        }

    }


  private void zzz()
  {
    jTextField8.getDocument().addDocumentListener(new DocumentListener()
    {
      public void changedUpdate(DocumentEvent e) {
        kembalian();
      }
      public void insertUpdate(DocumentEvent e) {
        kembalian();
      }
      public void removeUpdate(DocumentEvent e) {
        kembalian();
      }
    });
  }

  float cons;
  private void kembalian()
  {
    this.cons = 0;
    try {
      this.cons = Integer.valueOf(this.jTextField8.getText()).intValue();
    }
    catch (Exception z) {
      this.cons = 0;
    }
    jTextField9.setText("Rp. " + dfo.format(cons - grandTotal));
  }

    void lebarKolomTabel(){
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(370);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
    }
}
